### ISSUE TITLE
Initial package structure

### ISSUE THREAD

**Issue by jonaspiterek** [kitconcept/volto-quote-block#1]
# ToDo

- [x] statement (quote)
- [x] image
    - [x] alignment (left, right, centered)(implemented as a config option)
- [x] person
    - [x] name of the person
    - [x] additional data, e.g. position and/or date
